services:
  # --- User Microservice ---
  user-service:
    build:
      context: .
      dockerfile: app/user/Dockerfile
    # Override: Run the 'user' binary specifically
    command: ["./server", "-conf", "/data/conf"]
    ports:
      - "8000:8000" # HTTP
      - "9000:9000" # gRPC
    volumes:
      - ./app/user/configs:/data/conf
    depends_on:
      mysql:
        condition: service_healthy

  # --- Order Microservice ---
  # order-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # Override: Run the 'order' binary specifically
  #   command: ["./order", "-conf", "/data/conf"]
  #   ports:
  #     - "8001:8000" # Maps Host 8001 to Order's HTTP 8000
  #     - "9001:9000" # Maps Host 9001 to Order's gRPC 9000
  #   volumes:
  #     - ./app/order/configs:/data/conf
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yinni_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5


# services:
#   mysql:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: yinni_db
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: ["./yinni_backend", "-conf", "/data/conf"] 
#     ports:
#       - "8000:8000"
#       - "9000:9000"
#     volumes:
#       - ./configs:/data/conf
#     depends_on:
#       mysql:
#         condition: service_healthy
#     environment:
#       - DB_SOURCE=root:root@tcp(mysql:3306)/yinni_db?parseTime=True