server:
  http:
    addr: 0.0.0.0:${USER_HTTP_PORT}
    timeout: 1s
  grpc:
    addr: 0.0.0.0:${USER_GRPC_PORT}
    timeout: 1s

auth:
  jwt_secret: ${JWT_SECRET}
  jwt_expire: 3600

data:
  database:
    driver: mysql
    source: root:root@tcp(mysql:3306)/yinni_db?parseTime=true&charset=utf8mb4&loc=Local
