server:
  http:
    addr: 0.0.0.0:${USER_HTTP_PORT}
    timeout: 1s
  grpc:
    addr: 0.0.0.0:${USER_GRPC_PORT}
    timeout: 1s

auth:
  jwt_secret: ${JWT_SECRET}
  jwt_expire: ${JWT_EXPIRE}

data:
  database:
    driver: mysql
    source: ${DB_SOURCE}
