server:
  http:
    addr: 0.0.0.0:${AUTH_HTTP_PORT}
    timeout: 1s
  grpc:
    addr: 0.0.0.0:${AUTH_GRPC_PORT}
    timeout: 1s

auth:
  jwt_secret: ${JWT_SECRET}
  jwt_expire: 3600

data:
  database:
    driver: mysql
    source: ${DB_SOURCE}
